# Generated by Django 3.1.14 on 2022-12-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buah', '0005_auto_20221209_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
