# Generated by Django 3.1.14 on 2022-12-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buah', '0012_auto_20221210_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='jumlah',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
