# Generated by Django 4.1.4 on 2022-12-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buah', '0015_rename_date_orderd_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buahh',
            options={'verbose_name_plural': 'buahh'},
        ),
    ]
