# Generated by Django 4.1.4 on 2022-12-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buah', '0016_alter_buahh_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='buahh',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
